# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles JOM" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Qt\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Qt\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\ProgettiQt\Gestione_Riposo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\ProgettiQt\build_wasm_final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Qt\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Qt\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ProgettiQt\build_wasm_final\CMakeFiles C:\ProgettiQt\build_wasm_final\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ProgettiQt\build_wasm_final\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named appGestione_Riposo

# Build rule for target.
appGestione_Riposo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo
.PHONY : appGestione_Riposo

# fast build rule for target.
appGestione_Riposo\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\build
.PHONY : appGestione_Riposo\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_qmltyperegistration

# Build rule for target.
appGestione_Riposo_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_qmltyperegistration
.PHONY : appGestione_Riposo_qmltyperegistration

# fast build rule for target.
appGestione_Riposo_qmltyperegistration\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_qmltyperegistration.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_qmltyperegistration.dir\build
.PHONY : appGestione_Riposo_qmltyperegistration\fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmltyperegistrations.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\all_qmltyperegistrations.dir\build
.PHONY : all_qmltyperegistrations\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_qmllint

# Build rule for target.
appGestione_Riposo_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_qmllint
.PHONY : appGestione_Riposo_qmllint

# fast build rule for target.
appGestione_Riposo_qmllint\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_qmllint.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_qmllint.dir\build
.PHONY : appGestione_Riposo_qmllint\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_qmllint_json

# Build rule for target.
appGestione_Riposo_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_qmllint_json
.PHONY : appGestione_Riposo_qmllint_json

# fast build rule for target.
appGestione_Riposo_qmllint_json\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_qmllint_json.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_qmllint_json.dir\build
.PHONY : appGestione_Riposo_qmllint_json\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_qmllint_module

# Build rule for target.
appGestione_Riposo_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_qmllint_module
.PHONY : appGestione_Riposo_qmllint_module

# fast build rule for target.
appGestione_Riposo_qmllint_module\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_qmllint_module.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_qmllint_module.dir\build
.PHONY : appGestione_Riposo_qmllint_module\fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\all_qmllint.dir\build
.PHONY : all_qmllint\fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint_json.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\all_qmllint_json.dir\build
.PHONY : all_qmllint_json\fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_qmllint_module.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\all_qmllint_module.dir\build
.PHONY : all_qmllint_module\fast

#=============================================================================
# Target rules for targets named dump_qml_context_properties

# Build rule for target.
dump_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) dump_qml_context_properties
.PHONY : dump_qml_context_properties

# fast build rule for target.
dump_qml_context_properties\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\dump_qml_context_properties.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\dump_qml_context_properties.dir\build
.PHONY : dump_qml_context_properties\fast

#=============================================================================
# Target rules for targets named clean_qml_context_properties

# Build rule for target.
clean_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean_qml_context_properties
.PHONY : clean_qml_context_properties

# fast build rule for target.
clean_qml_context_properties\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clean_qml_context_properties.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\clean_qml_context_properties.dir\build
.PHONY : clean_qml_context_properties\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_copy_qml

# Build rule for target.
appGestione_Riposo_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_copy_qml
.PHONY : appGestione_Riposo_copy_qml

# fast build rule for target.
appGestione_Riposo_copy_qml\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_copy_qml.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_copy_qml.dir\build
.PHONY : appGestione_Riposo_copy_qml\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_copy_res

# Build rule for target.
appGestione_Riposo_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_copy_res
.PHONY : appGestione_Riposo_copy_res

# fast build rule for target.
appGestione_Riposo_copy_res\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_copy_res.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_copy_res.dir\build
.PHONY : appGestione_Riposo_copy_res\fast

#=============================================================================
# Target rules for targets named generate_qmlls_build_ini_file

# Build rule for target.
generate_qmlls_build_ini_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) generate_qmlls_build_ini_file
.PHONY : generate_qmlls_build_ini_file

# fast build rule for target.
generate_qmlls_build_ini_file\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\generate_qmlls_build_ini_file.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\generate_qmlls_build_ini_file.dir\build
.PHONY : generate_qmlls_build_ini_file\fast

#=============================================================================
# Target rules for targets named module_appGestione_Riposo_aotstats_target

# Build rule for target.
module_appGestione_Riposo_aotstats_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) module_appGestione_Riposo_aotstats_target
.PHONY : module_appGestione_Riposo_aotstats_target

# fast build rule for target.
module_appGestione_Riposo_aotstats_target\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\module_appGestione_Riposo_aotstats_target.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\module_appGestione_Riposo_aotstats_target.dir\build
.PHONY : module_appGestione_Riposo_aotstats_target\fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\all_aotstats.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\all_aotstats.dir\build
.PHONY : all_aotstats\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_autogen_timestamp_deps

# Build rule for target.
appGestione_Riposo_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_autogen_timestamp_deps
.PHONY : appGestione_Riposo_autogen_timestamp_deps

# fast build rule for target.
appGestione_Riposo_autogen_timestamp_deps\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_autogen_timestamp_deps.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_autogen_timestamp_deps.dir\build
.PHONY : appGestione_Riposo_autogen_timestamp_deps\fast

#=============================================================================
# Target rules for targets named appGestione_Riposo_autogen

# Build rule for target.
appGestione_Riposo_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) appGestione_Riposo_autogen
.PHONY : appGestione_Riposo_autogen

# fast build rule for target.
appGestione_Riposo_autogen\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo_autogen.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo_autogen.dir\build
.PHONY : appGestione_Riposo_autogen\fast

.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.o: .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.o
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.o

# target to build an object file
.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.o
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.o

.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.i: .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.i
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.i

# target to preprocess a source file
.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.i
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.i

.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.s: .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.s
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.s

# target to generate assembly for a file
.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.s
.PHONY : .qt\rcc\qrc_appGestione_Riposo_raw_qml_0.cpp.s

.qt\rcc\qrc_qmake_Gestione_Riposo.o: .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.o
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.o

# target to build an object file
.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.o
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.o

.qt\rcc\qrc_qmake_Gestione_Riposo.i: .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.i
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.i

# target to preprocess a source file
.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.i
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.i

.qt\rcc\qrc_qmake_Gestione_Riposo.s: .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.s
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.s

# target to generate assembly for a file
.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.qt\rcc\qrc_qmake_Gestione_Riposo.cpp.s
.PHONY : .qt\rcc\qrc_qmake_Gestione_Riposo.cpp.s

.rcc\qmlcache\appGestione_Riposo_Main_qml.o: .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.o
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.o

# target to build an object file
.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.o
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.o

.rcc\qmlcache\appGestione_Riposo_Main_qml.i: .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.i
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.i

# target to preprocess a source file
.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.i
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.i

.rcc\qmlcache\appGestione_Riposo_Main_qml.s: .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.s
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.s

# target to generate assembly for a file
.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.s
.PHONY : .rcc\qmlcache\appGestione_Riposo_Main_qml.cpp.s

.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.o: .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.o
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.o

# target to build an object file
.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.o
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.o

.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.i: .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.i
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.i

# target to preprocess a source file
.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.i
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.i

.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.s: .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.s
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.s

# target to generate assembly for a file
.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\.rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.s
.PHONY : .rcc\qmlcache\appGestione_Riposo_qmlcache_loader.cpp.s

appGestione_Riposo_autogen\mocs_compilation.o: appGestione_Riposo_autogen\mocs_compilation.cpp.o
.PHONY : appGestione_Riposo_autogen\mocs_compilation.o

# target to build an object file
appGestione_Riposo_autogen\mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appGestione_Riposo_autogen\mocs_compilation.cpp.o
.PHONY : appGestione_Riposo_autogen\mocs_compilation.cpp.o

appGestione_Riposo_autogen\mocs_compilation.i: appGestione_Riposo_autogen\mocs_compilation.cpp.i
.PHONY : appGestione_Riposo_autogen\mocs_compilation.i

# target to preprocess a source file
appGestione_Riposo_autogen\mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appGestione_Riposo_autogen\mocs_compilation.cpp.i
.PHONY : appGestione_Riposo_autogen\mocs_compilation.cpp.i

appGestione_Riposo_autogen\mocs_compilation.s: appGestione_Riposo_autogen\mocs_compilation.cpp.s
.PHONY : appGestione_Riposo_autogen\mocs_compilation.s

# target to generate assembly for a file
appGestione_Riposo_autogen\mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appGestione_Riposo_autogen\mocs_compilation.cpp.s
.PHONY : appGestione_Riposo_autogen\mocs_compilation.cpp.s

appgestione_riposo_qmltyperegistrations.o: appgestione_riposo_qmltyperegistrations.cpp.o
.PHONY : appgestione_riposo_qmltyperegistrations.o

# target to build an object file
appgestione_riposo_qmltyperegistrations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appgestione_riposo_qmltyperegistrations.cpp.o
.PHONY : appgestione_riposo_qmltyperegistrations.cpp.o

appgestione_riposo_qmltyperegistrations.i: appgestione_riposo_qmltyperegistrations.cpp.i
.PHONY : appgestione_riposo_qmltyperegistrations.i

# target to preprocess a source file
appgestione_riposo_qmltyperegistrations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appgestione_riposo_qmltyperegistrations.cpp.i
.PHONY : appgestione_riposo_qmltyperegistrations.cpp.i

appgestione_riposo_qmltyperegistrations.s: appgestione_riposo_qmltyperegistrations.cpp.s
.PHONY : appgestione_riposo_qmltyperegistrations.s

# target to generate assembly for a file
appgestione_riposo_qmltyperegistrations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\appgestione_riposo_qmltyperegistrations.cpp.s
.PHONY : appgestione_riposo_qmltyperegistrations.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\appGestione_Riposo.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\appGestione_Riposo.dir\main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... all_aotstats
	@echo ... all_qmllint
	@echo ... all_qmllint_json
	@echo ... all_qmllint_module
	@echo ... all_qmltyperegistrations
	@echo ... appGestione_Riposo_autogen
	@echo ... appGestione_Riposo_autogen_timestamp_deps
	@echo ... appGestione_Riposo_copy_qml
	@echo ... appGestione_Riposo_copy_res
	@echo ... appGestione_Riposo_qmllint
	@echo ... appGestione_Riposo_qmllint_json
	@echo ... appGestione_Riposo_qmllint_module
	@echo ... appGestione_Riposo_qmltyperegistration
	@echo ... clean_qml_context_properties
	@echo ... dump_qml_context_properties
	@echo ... generate_qmlls_build_ini_file
	@echo ... module_appGestione_Riposo_aotstats_target
	@echo ... appGestione_Riposo
	@echo ... .qt/rcc/qrc_appGestione_Riposo_raw_qml_0.o
	@echo ... .qt/rcc/qrc_appGestione_Riposo_raw_qml_0.i
	@echo ... .qt/rcc/qrc_appGestione_Riposo_raw_qml_0.s
	@echo ... .qt/rcc/qrc_qmake_Gestione_Riposo.o
	@echo ... .qt/rcc/qrc_qmake_Gestione_Riposo.i
	@echo ... .qt/rcc/qrc_qmake_Gestione_Riposo.s
	@echo ... .rcc/qmlcache/appGestione_Riposo_Main_qml.o
	@echo ... .rcc/qmlcache/appGestione_Riposo_Main_qml.i
	@echo ... .rcc/qmlcache/appGestione_Riposo_Main_qml.s
	@echo ... .rcc/qmlcache/appGestione_Riposo_qmlcache_loader.o
	@echo ... .rcc/qmlcache/appGestione_Riposo_qmlcache_loader.i
	@echo ... .rcc/qmlcache/appGestione_Riposo_qmlcache_loader.s
	@echo ... appGestione_Riposo_autogen/mocs_compilation.o
	@echo ... appGestione_Riposo_autogen/mocs_compilation.i
	@echo ... appGestione_Riposo_autogen/mocs_compilation.s
	@echo ... appgestione_riposo_qmltyperegistrations.o
	@echo ... appgestione_riposo_qmltyperegistrations.i
	@echo ... appgestione_riposo_qmltyperegistrations.s
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

